openapi: 3.0.3
info:
  title: Publisher API
  description: API for publishing content to social media platforms
  version: 1.0.0
  contact:
    name: AutoGenSocial Team

servers:
  - url: https://publisher.autogensocial.example.com/v1
    description: Production server
  - url: http://localhost:7073/api
    description: Local development server

tags:
  - name: publish
    description: Content publishing operations
  - name: connections
    description: Social media platform connections
  - name: analytics
    description: Post analytics and metrics

paths:
  /publish:
    post:
      tags:
        - publish
      summary: Publish a post to social media platform(s)
      operationId: publishPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postId:
                  type: string
                  description: ID of the post to publish
                platforms:
                  type: array
                  items:
                    type: string
                    enum: [twitter, facebook, instagram, linkedin, tiktok]
                  description: Target platforms for publishing
                scheduledTime:
                  type: string
                  format: date-time
                  description: Optional scheduled time for publishing
              required:
                - postId
                - platforms
      responses:
        '200':
          description: Post published or scheduled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublishResult'
        '400':
          description: Invalid request
        '401':
          description: Platform authentication required

  /publish/{publishId}/status:
    get:
      tags:
        - publish
      summary: Get publishing status
      operationId: getPublishStatus
      parameters:
        - name: publishId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublishStatus'

  /connections:
    get:
      tags:
        - connections
      summary: List all platform connections
      operationId: listConnections
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PlatformConnection'
    post:
      tags:
        - connections
      summary: Create a new platform connection
      operationId: createConnection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlatformConnection'
      responses:
        '201':
          description: Connection created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlatformConnection'

  /analytics/{postId}:
    get:
      tags:
        - analytics
      summary: Get analytics for a published post
      operationId: getPostAnalytics
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostAnalytics'

components:
  schemas:
    PublishResult:
      type: object
      properties:
        publishId:
          type: string
        postId:
          type: string
        status:
          type: string
          enum: [queued, scheduled, publishing, published, failed]
        platforms:
          type: array
          items:
            type: object
            properties:
              platform:
                type: string
              status:
                type: string
              platformPostId:
                type: string
              error:
                type: string
        scheduledTime:
          type: string
          format: date-time
        publishedTime:
          type: string
          format: date-time
      required:
        - publishId
        - postId
        - status
        - platforms

    PublishStatus:
      type: object
      properties:
        publishId:
          type: string
        status:
          type: string
        platforms:
          type: array
          items:
            type: object
        lastUpdated:
          type: string
          format: date-time

    PlatformConnection:
      type: object
      properties:
        id:
          type: string
        platform:
          type: string
          enum: [twitter, facebook, instagram, linkedin, tiktok]
        accountName:
          type: string
        accountId:
          type: string
        status:
          type: string
          enum: [active, inactive, expired]
        connectedAt:
          type: string
          format: date-time
      required:
        - id
        - platform
        - status

    PostAnalytics:
      type: object
      properties:
        postId:
          type: string
        platform:
          type: string
        metrics:
          type: object
          properties:
            impressions:
              type: integer
            engagements:
              type: integer
            likes:
              type: integer
            shares:
              type: integer
            comments:
              type: integer
            clicks:
              type: integer
        lastUpdated:
          type: string
          format: date-time
