# generated by datamodel-codegen:
#   filename:  brand.json

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class Voice(BaseModel):
    tone: Optional[List[str]] = Field(
        None,
        description='List of tone attributes (e.g., professional, friendly, casual)',
    )
    style: Optional[str] = Field(None, description='Writing style guidelines')


class Colors(BaseModel):
    primary: Optional[str] = Field(None, description='Primary brand color (hex)')
    secondary: Optional[str] = Field(None, description='Secondary brand color (hex)')
    accent: Optional[List[str]] = Field(None, description='Accent colors (hex)')


class Heading(BaseModel):
    family: Optional[str] = Field(None, description='Font family name for headings')
    weight: Optional[str] = Field(
        None, description="Font weight for headings (e.g., 'bold', '700')"
    )
    style: Optional[str] = Field(
        None, description="Font style for headings (e.g., 'normal', 'italic')"
    )


class Body(BaseModel):
    family: Optional[str] = Field(None, description='Font family name for body text')
    weight: Optional[str] = Field(
        None, description="Font weight for body text (e.g., 'normal', '400')"
    )
    style: Optional[str] = Field(
        None, description="Font style for body text (e.g., 'normal', 'italic')"
    )


class Accent(BaseModel):
    family: Optional[str] = Field(None, description='Font family name for accent text')
    weight: Optional[str] = Field(None, description='Font weight for accent text')
    style: Optional[str] = Field(None, description='Font style for accent text')


class Fonts(BaseModel):
    heading: Optional[Heading] = Field(None, description='Font settings for headings')
    body: Optional[Body] = Field(None, description='Font settings for body text')
    accent: Optional[Accent] = Field(
        None, description='Font settings for accent/special text'
    )


class VisualStyles(BaseModel):
    colors: Optional[Colors] = Field(None, description='Brand color palette')
    fonts: Optional[Fonts] = Field(
        None, description='Typography guidelines for the brand'
    )


class Logo(BaseModel):
    url: Optional[AnyUrl] = Field(None, description='URL to the logo image')
    variants: Optional[Dict[str, Any]] = Field(
        None, description='Different logo variants (light, dark, etc.)'
    )


class Platform(Enum):
    instagram = 'instagram'
    facebook = 'facebook'
    twitter = 'twitter'
    linkedin = 'linkedin'
    tiktok = 'tiktok'
    youtube = 'youtube'


class PostingPermissions(BaseModel):
    canPost: Optional[bool] = Field(False, description='Permission to create posts')
    canSchedule: Optional[bool] = Field(
        False, description='Permission to schedule posts'
    )
    canDelete: Optional[bool] = Field(False, description='Permission to delete posts')


class SocialAccount(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    platform: Platform = Field(..., description='Social media platform name')
    handle: str = Field(
        ..., description='Social media handle/username (without @ symbol)'
    )
    displayName: Optional[str] = Field(None, description='Display name for the account')
    url: Optional[AnyUrl] = Field(
        None, description='Direct URL to the social media profile'
    )
    isActive: Optional[bool] = Field(
        True, description='Whether this account is actively used for posting'
    )
    postingPermissions: Optional[PostingPermissions] = Field(
        None, description='Permissions and capabilities for this account'
    )


class Brand(BaseModel):
    id: str = Field(..., description='Unique identifier for the brand')
    name: str = Field(..., description='Brand name')
    description: Optional[str] = Field(None, description='Brand description')
    voice: Optional[Voice] = Field(None, description='Brand voice and tone guidelines')
    visualStyles: Optional[VisualStyles] = Field(
        None, description='Visual styling guidelines for the brand'
    )
    socialAccounts: Optional[List[SocialAccount]] = Field(
        None, description='Social media accounts associated with the brand'
    )
    logo: Optional[Logo] = Field(None, description='Brand logo assets')
