# generated by datamodel-codegen:
#   filename:  post.json

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field, conint, constr


class Platform(Enum):
    twitter = 'twitter'
    facebook = 'facebook'
    instagram = 'instagram'
    linkedin = 'linkedin'
    tiktok = 'tiktok'


class ImageCaption(BaseModel):
    imageIndex: conint(ge=0) = Field(
        ..., description='Index of the image this caption applies to'
    )
    caption: str = Field(..., description='Caption text for this specific image')


class Content(BaseModel):
    mainCopy: str = Field(..., description='Main post text/caption')
    imageCaptions: Optional[List[ImageCaption]] = Field(
        None, description='Individual captions for each image (for carousel posts)'
    )
    comments: Optional[List[str]] = Field(
        None, description='Additional comments or supporting text'
    )
    hashtags: Optional[List[constr(pattern=r'^#[a-zA-Z0-9_]+$')]] = Field(
        None, description='Hashtags to include (with # prefix)'
    )


class Type(Enum):
    image = 'image'
    video = 'video'
    gif = 'gif'


class MediaItem(BaseModel):
    type: Type
    url: AnyUrl
    altText: Optional[str] = None


class Status(Enum):
    draft = 'draft'
    scheduled = 'scheduled'
    published = 'published'
    failed = 'failed'


class Metrics(BaseModel):
    impressions: Optional[int] = None
    engagements: Optional[int] = None
    likes: Optional[int] = None
    shares: Optional[int] = None
    comments: Optional[int] = None


class Post(BaseModel):
    id: str = Field(..., description='Unique identifier for the post')
    postPlanId: Optional[str] = Field(
        None, description='Reference to the parent post plan'
    )
    brandId: str = Field(..., description='Reference to the brand')
    platform: Platform = Field(..., description='Target social media platform')
    content: Content = Field(..., description='Post content')
    media: Optional[List[MediaItem]] = Field(None, description='Media attachments')
    scheduledTime: Optional[AwareDatetime] = Field(
        None, description='Scheduled publication time'
    )
    publishedTime: Optional[AwareDatetime] = Field(
        None, description='Actual publication time'
    )
    status: Status = Field(..., description='Current status of the post')
    metrics: Optional[Metrics] = Field(None, description='Post performance metrics')
    createdAt: Optional[AwareDatetime] = None
    updatedAt: Optional[AwareDatetime] = None
