# generated by datamodel-codegen:
#   filename:  postPlan.json

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import AwareDatetime, BaseModel, Field, conint, constr


class PostType(Enum):
    images = 'images'
    video = 'video'


class Orientation(Enum):
    portrait = 'portrait'
    landscape = 'landscape'
    square = 'square'


class TextOverlay(BaseModel):
    content: Optional[str] = Field(None, description='Text content to overlay')
    style: Optional[str] = Field(None, description='Style specification for the text')
    position: Optional[str] = Field(None, description='Position of text on the image')


class Image(BaseModel):
    description: str = Field(..., description='Description of the image content')
    layout: str = Field(..., description='Layout specification for the image')
    textOverlay: Optional[TextOverlay] = Field(
        None, description='Text or comment overlay specifications'
    )


class MediaContent(BaseModel):
    type: Literal['images']
    imageCount: conint(ge=1, le=10) = Field(
        ..., description='Number of images (1 for single image, multiple for carousel)'
    )
    orientation: Orientation = Field(
        ..., description='Image orientation/aspect ratio for all images in this post'
    )
    images: List[Image] = Field(..., description='Array of image specifications')


class TextOverlay1(BaseModel):
    content: Optional[str] = Field(None, description='Text content to overlay')
    style: Optional[str] = Field(None, description='Style specification for the text')
    position: Optional[str] = Field(None, description='Position of text on the video')


class Video(BaseModel):
    description: str = Field(..., description='Description of the video content')
    layout: str = Field(..., description='Layout specification for the video')
    textOverlay: Optional[TextOverlay1] = Field(
        None, description='Text or comment overlay specifications'
    )


class MediaContent1(BaseModel):
    type: Literal['video']
    orientation: Orientation = Field(..., description='Video orientation/aspect ratio')
    video: Video = Field(..., description='Video specification')


class Platform(Enum):
    twitter = 'twitter'
    facebook = 'facebook'
    instagram = 'instagram'
    linkedin = 'linkedin'
    tiktok = 'tiktok'


class Scheduling(BaseModel):
    type: Literal['one-time']
    publishAt: AwareDatetime = Field(
        ..., description='Specific date and time to publish'
    )


class Frequency(Enum):
    daily = 'daily'
    weekly = 'weekly'
    monthly = 'monthly'


class Scheduling1(BaseModel):
    type: Literal['recurring']
    frequency: Frequency = Field(..., description='How often to repeat')
    time: constr(pattern=r'^([01]?[0-9]|2[0-3]):[0-5][0-9]$') = Field(
        ..., description='Time of day in HH:MM format (24-hour)'
    )
    dayOfWeek: Optional[conint(ge=0, le=6)] = Field(
        None,
        description='Day of week (0=Sunday, 6=Saturday) - required for weekly frequency',
    )
    dayOfMonth: Optional[conint(ge=1, le=31)] = Field(
        None, description='Day of month - required for monthly frequency'
    )
    startDate: date = Field(..., description='When to start the recurring schedule')
    endDate: Optional[date] = Field(
        None, description='When to stop the recurring schedule (optional)'
    )
    nextRunDate: Optional[AwareDatetime] = Field(
        None, description='The next scheduled execution time (updated after each run)'
    )


class ContentGuidelines(BaseModel):
    topics: Optional[List[str]] = None
    keywords: Optional[List[str]] = None
    tone: Optional[str] = None


class Status(Enum):
    draft = 'draft'
    approved = 'approved'
    scheduled = 'scheduled'
    published = 'published'


class PostPlan(BaseModel):
    id: str = Field(..., description='Unique identifier for the post plan')
    brandId: str = Field(..., description='Reference to the brand')
    title: str = Field(..., description='Post plan title')
    objective: Optional[str] = Field(
        None, description='Marketing objective for this post plan'
    )
    postType: Optional[PostType] = Field(
        None, description='Type of media content for the post'
    )
    mediaContent: Union[MediaContent, MediaContent1] = Field(
        ..., description='Media content specifications'
    )
    platforms: List[Platform] = Field(..., description='Target social media platforms')
    scheduling: Optional[Union[Scheduling, Scheduling1]] = Field(
        None, description='Post scheduling configuration'
    )
    contentGuidelines: Optional[ContentGuidelines] = Field(
        None, description='Content creation guidelines'
    )
    status: Status = Field(..., description='Current status of the post plan')
    createdAt: Optional[AwareDatetime] = None
    updatedAt: Optional[AwareDatetime] = None
