# generated by datamodel-codegen:
#   filename:  socialAccount.json

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import AnyUrl, BaseModel, ConfigDict, Field


class Platform(Enum):
    instagram = 'instagram'
    facebook = 'facebook'
    twitter = 'twitter'
    linkedin = 'linkedin'
    tiktok = 'tiktok'
    youtube = 'youtube'


class PostingPermissions(BaseModel):
    canPost: Optional[bool] = Field(False, description='Permission to create posts')
    canSchedule: Optional[bool] = Field(
        False, description='Permission to schedule posts'
    )
    canDelete: Optional[bool] = Field(False, description='Permission to delete posts')


class SocialAccount(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    platform: Platform = Field(..., description='Social media platform name')
    handle: str = Field(
        ..., description='Social media handle/username (without @ symbol)'
    )
    displayName: Optional[str] = Field(None, description='Display name for the account')
    url: Optional[AnyUrl] = Field(
        None, description='Direct URL to the social media profile'
    )
    isActive: Optional[bool] = Field(
        True, description='Whether this account is actively used for posting'
    )
    postingPermissions: Optional[PostingPermissions] = Field(
        None, description='Permissions and capabilities for this account'
    )
